@startuml
class PriorityQueue<T> {
 isEmpty
 PriorityQueue(heap=new BinaryHeap())
 insert(key, value)
 pull()
}

PriorityQueue --> Heap
abstract class Heap<T extends Number> {
  heap: T[]
  getSize()
  Heap(comparator=min)
  isEmpty()
  insert(...T)
  getPeek(): T
  extractPeek(): T
  replace()
  heapify()
  iterator
  meld()
  merge(Heap)
}

class BinaryHeap extends Heap
class LeftistHeap extends Heap
class BinomialHeap extends Heap
class FibonacciHeap extends Heap
class PairingHeap extends Heap
class BrodalHeap extends Heap
class RankpairingHeap extends Heap
class StrictFibonacciHeap extends Heap
class TwoTreeHeap extends Heap

@enduml